### ISSUE TITLE
Change example code to new snake case methods

### ISSUE THREAD

**Issue by d-krupke** [d-krupke/cpsat-primer#34]
OR-Tools now has the pythonic snake case convention as default, while still having backwards compatibility to the old Google-style. I have already updated the text, but the examples are still in the old style. Would be great to update them, too.

**Comment by greenLeopard** [comment]
@d-krupke if PR #54 covers this issue, shall we mark it as closed? :)

**Comment by d-krupke** [comment]
Oh, of course! Thanks for reminding me :)
