### ISSUE TITLE
Proper Example for Reservoir Constraint

### ISSUE THREAD

**Issue by d-krupke** [d-krupke/cpsat-primer#37]
The Reservoir Constraint could need a good example. I tried to quickly build one but the constraint is not trivial to use and the example did not work out. Unfortunately, there are a lot of other areas that need attention more urgently so I do not know when I would find the time myself.

The example could be added directly in the text, like for the other advanced constraints.

**Comment by michip** [comment]
I was working on a non-trivial example for the reservoir constraints last week. My problem is a bit artificial. As soon as I find a better motivation and some spare time I will add that to the text.

**Comment by michip** [comment]
I have added a section with an example in the `reservoir_constraints` branch. The Jupyter Notebook contains no text; I want to copy it from the section once it is revised. I would happily receive feedback and make further changes/extensions if necessary.
