### ISSUE TITLE
Instructions for a local build

### ISSUE THREAD

**Issue by leonlan** [d-krupke/cpsat-primer#43]
I realized that one of my "fixes" in #41 instead did not fix. Locally building the book would have helped prevent that, and it would be helpful to have instructions to build this book locally described somewhere.

Based on https://github.com/d-krupke/cpsat-primer/blob/main/.github/workflows/deploy.yml:
- Install `mdbook`
- Run `python3 build.py`
- `cd .mdbook`
- `mdbook build`
- `mdbook watch --open .`

What's a good place to describe these instructions?

**Comment by d-krupke** [comment]
A great place would be to create a file `CONTRIBUTING.md` that will contain general information for anyone wanting to contribute.

**Comment by leonlan** [comment]
OK, I'll make a PR for this tomorrow!
