### ISSUE TITLE
Suggestions for chapter 4: basic modeling

### ISSUE THREAD

**Issue by leonlan** [d-krupke/cpsat-primer#47]
Some suggestions for chapter 4 that may need discussion before implementing. Once we have agreed on how to proceed I'll make a PR for the changes.

- [x] Is the `new_constant` any useful? I cannot think of any reasons. If not, then we could just remove this part.

  > Additionally, there is the new_constant-method, which allows you to create a variable that is constant. I have not found a use case for this yet, let me know if you have one.

- [x] The paragraphs on domain variables can use a small example to illustrate the meaning. The naming of "domain" variables is a bit unfortunate because integer variables also have a domain which made me confused. My suggestion is to change the following sentence:

  > Unlike regular integer variables, domain variables are tailored to represent a specific set of values.

  to something like this:

  > Unlike regular integer variables, which must have a domain between a given range of values (e.g., [1, 100]), domain variables can specify a custom set of values as domain (e.g., {1, 3, 5}).

- [x] Do you want to use the new PEP8 style everywhere? There are still some places where you use the old style (`x_vars[i].Not()`). Related https://github.com/d-krupke/cpsat-primer/issues/34.

- [x] In subsection [Adding Logical AND Constraints](https://d-krupke.github.io/cpsat-primer/04_modelling.html#adding-logical-and-constraints): after explaining the `add_bool_and` there is a paragraph on reification:

   > The add_bool_and method is most effective when used with the only_enforce_if method. For cases not utilizing only_enforce_if a simple AND-clause such as (b1∧¬b2∧¬b3) becomes redundant by simply substituting b1 with 1 and \( b_2, \\)b_3 with 0. In straightforward scenarios, consider substituting these variables with their constant values to reduce unnecessary complexity, especially in larger models where size and manageability are concerns. In smaller or simpler models, CP-SAT efficiently handles these redundancies, allowing you to focus on maintaining clarity and readability in your model.

   This section comes too early: the reader does not yet know what reification is. I think this paragraph should be moved to the corresponding section.

**Comment by d-krupke** [comment]
Regarding `new_constant`: It seems to be handled differently than a common coefficient. More like a constant variable that is probably more expensive. Internally, CP-SAT probably handles them equally, but at least on the interface level, they seem to go into different containers. I added it for completeness, though, I don't think it to be useful.

Argument for deleting it: Text becomes simpler

Argument for keeping it: A user may stumble upon it during in the docs or in autocomplete.

**Comment by d-krupke** [comment]
Regarding domain variables: What about naming them more explicitly, e.g., "Custom Domain Variables"?

I like your new text! Let us add that.

**Comment by d-krupke** [comment]
PEP8: Yes, I would like to have the new variant everywhere, except once in the beginning, so users are not surprised when they stumble on the old style (snake case vs camel case is self explanatory, but ~ vs Not isn't).

If I missed it somewhere, I would greatly appreciate it to be updated :)

**Comment by d-krupke** [comment]
> From what i understand, the `new_constant` method can be used as a  placeholder for type-consistency. See examples in [scheduling](https://github.com/google/or-tools/blob/2c333f58a37d7c75d29a58fd772c9b3f94e2ca1c/ortools/sat/docs/scheduling.md?plain=1#L1227) and [rcpsp](https://github.com/google/or-tools/blob/2c333f58a37d7c75d29a58fd772c9b3f94e2ca1c/examples/python/rcpsp_sat.py#L359). 
> 
> 
> 
> Quite useless imo but i suppose its worth noting as users may come across it. 

Thanks for the examples. :) The type-consistency should only be an issue with older Python versions. The types in the library are properly defined, and should not require this special type, AFAIK. I would guess that this is a fragment that is required in other languages and they just also added it to the Python interface.

Maybe we should shorten it to a tiny side note, just in case the user has seen it somewhere. However, it also makes sense to just not mention things that are not useful. Students often remember keywords without remembering the "bad" part. 😅

**Comment by leonlan** [comment]
I'm leaning toward not mentioning it if it doesn't have any clear benefits. (I already consider the current text to be a tiny side note.)

@d-krupke what do you think of the last point related `add_bool_and`?

**Comment by d-krupke** [comment]
> I'm leaning toward not mentioning it if it doesn't have any clear benefits. (I already consider the current text to be a tiny side note.)

I just asked the developers if there actually is a use case for `new_constant`. Maybe we get an answer regarding that.

Otherwise, how about adding a section at the end like "Further Notes", were we just list such comments, without having them in the main text? Just for completeness.

> 
> @d-krupke what do you think of the last point related `add_bool_and`?

Seems like I forgot to press the button after writing my comment. How about moving it to reification and adding a sentence to `add_bool_and` mentioning that this constraint will only become useful in the context of reification, discussed later?

**Comment by d-krupke** [comment]
Ok, so `new_constant` can actually be useful for booleans, as `new_constant` allows to use `~`. If one would have a container, e.g., a dictionary of boolean variables, one could replace some of the variables by constants with `new_constant` (assume you were able to fix these based on some domain logic).
If one would just use `int`s, they could not be a full drop-in because the int's will have a different behavior for `~`.

So `new_constant` should not be considered as coefficient, but as constant variables. While `int`s should be able to serve as drop-ins for IntVars, they do not work as drop-ins for BoolVars.

I have to admit that I actually got it wrong in my head because I thought `new_constant`==coefficient. But it is a variable that is constant.

**Comment by d-krupke** [comment]
So, my suggestion is to write something like:
"Additionally, there is the `new_constant`-method, which allows you to create a variable that is constant. This allows you to safely replace variables by constants, which is primarily useful for boolean variables. Constant integer variables can in most cases be simply replaced by plain integers."

**Comment by leonlan** [comment]
Sounds good! I'm a bit short on time right now but will do this tomorrow (and hopefully also have all the other suggestions organized).
