### ISSUE TITLE
Suggestions for Chapter 6: Parameters

### ISSUE THREAD

**Issue by leonlan** [d-krupke/cpsat-primer#49]
- [x] Style: I think it's a bit too much to list all the (sub-)solvers used in
https://d-krupke.github.io/cpsat-primer/05_parameters.html#parallelization. The current layout makes it hard to read and it is a lot of information that might not be relevant to readers. Is there a reference that we can refer to instead, or can we think of a better way of visualizing this as a table?
- [ ] Content: I have seem multiple times Laurent Perron mention that it is really recommended to use OR-Tools with 8 cores, or even 16 cores. Should we mention this somewhere in the parallelization section as well?
- [x] Content: We could also mention what the default setting of the solver is regarding parallelization, which is to use all available cores by default right?
- [x] Structure: There are three sections that are not strictly "parameters" (exporting model, adding assumptions, adding hints). The section then ends with "decision strategy", which is a parameter again. I don't think this is problematic but I noticed it.
- [x] Structure: I think it's easier to start with hints first and then discuss assumptions. Hints are similar to warm-starts, which most readers understand. Assumptions are more niche because they only apply to boolean variables.
- [x] Content: The assumptions section starts begin with
  >"Often, you may need to explore the impact of forcing certain variables to specific values."

  This is a bit deceptive because assumptions can only force boolean variables. In combination with the restructuring point above I suggest 1) discussing parameter "fix_variables_to_their_hinted_value" in the hints section, which does practically the same 2) rewriting the assumptions section to emphasize that this is only for fixing bools.
- [ ] New content: This section starts with a brief mention of protobufs. This was a completely new concept to me when I started reading into OR-Tools but it's a common practice by Google and similar ideas apply to other software (e.g., intermediate data representation for modeling APIs). Perhaps we can add a section to the advanced topics on protobufs? I can make a separate issue for that.

**Comment by d-krupke** [comment]
The list of subsolver: You are right, this is terrible. I will try to think of a solution. There is no real reference for this, but we can try to extract it into a separate document.

**Comment by d-krupke** [comment]
Regarding Laurent's recommendation: There is some mention of number of cores in the hardware section, but we could be more explicity. We could also explicitly mention the recommendation in the hardware section. At the same time, the influence of the number of cores is quite complex - I actually had performance degradations when using too many cores for one problem, and for some problems you have nearly the same performance with only a single core.

**Comment by d-krupke** [comment]
Regarding default number of workers: Yes, we should definitely mention that. If I remember correctly, this was different in the past, but now it will use all the cores by default.

**Comment by d-krupke** [comment]
Regarding structure and things not being parameters: Good point, not critical but still kind of ugly. I am also planning to do a little more stuff on parameter tuning, so we could think of splitting these parts into a separate chapter.

**Comment by d-krupke** [comment]
>  Structure: I think it's easier to start with hints first and then discuss assumptions. Hints are similar to warm-starts, which most readers understand. Assumptions are more niche because they only apply to boolean variables.

Assumptions are actually a common technique in the SAT-community, and allow some nice tricks there. But I agree with you, let us change that. Also, the asumptions are not too useful in CP-SAT as CP-SAT does not remember any learned clauses or anything like that. Allows still some tricks, though, it is indeed rather a niche due to its limitations.

**Comment by d-krupke** [comment]
>  Content: The assumptions section starts begin with
Good idea, I like your recommendation :)

**Comment by d-krupke** [comment]
>  New content: This section starts with a brief mention of protobufs. This was a completely new concept to me when I started reading into OR-Tools but it's a common practice by Google and similar ideas apply to other software (e.g., intermediate data representation for modeling APIs). Perhaps we can add a section to the advanced topics on protobufs? I can make a separate issue for that.

This is actually a good idea, however, I would give it a lower priority as it is, as you said, quite common also in other contexts. I could imagine a section that shows how the protobuf of a model looks like and the basic concepts of protobuf, with references for more details. This way we would keep the focus on CP-SAT but give an idea and pointer for what happens under the hood, especially since the protobuf allows to do some nice hacks to overcome shortcomings in the interface.

**Comment by d-krupke** [comment]
I just started developing a tuning tool for the parameters, which could be a good extension to this chapter. However, it is still in a very early phase.

https://github.com/d-krupke/cpsat-autotune
